sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  matrix:
      - DJANGO="Django<1.9"
      - DJANGO="Django<1.0"
      - DJANGO="Django<1.11"
      - DJANGO=master
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install -r requirements.txt
  - pip install tox tox-travis
maxtix:
  exclude:
    - python: "3.3"
      env: DJANGO="Django>1.10"
    - python: "3.3"
      env: DJANGO="Djajgo<1.11"
branches:
  - master
  - develop
script:
  - tox
after_success:
  - pip install codecov
  - codecov -e TOXENV,DJANGO
notifications:
  email: false
