sudo: false
dist: xenial
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install tox-travis
  - pip install "tox>=1.8"
  - pip install coverage coveralls
branches:
  only:
  - master
  - develop
script:
  - tox -r
after_success:
  - coverage report
  - coveralls
