# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20170528_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='use_sandbox',
            field=models.BooleanField(default=True),
        ),
    ]
