# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-18 04:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_devicetoken_use_sandbox'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certfile',
            options={'verbose_name': 'Certificate files', 'verbose_name_plural': 'Certificate file'},
        ),
        migrations.AlterModelOptions(
            name='devicetoken',
            options={'verbose_name': 'Device Tokens', 'verbose_name_plural': 'Device Token'},
        ),
    ]
