# Generated by Django 2.0.6 on 2018-06-15 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_auto_20180218_0454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certfile',
            old_name='date',
            new_name='expire_date',
        ),
        migrations.AddField(
            model_name='certfile',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
